/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.host;

import Business.Business;
import Business.Enterprise.Event;
import Business.Organization.HostOrganization.HostOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author godalla
 */
public class EventRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventRequestPanel
     */
    JPanel workArea;
    HostOrganization organization;
    Business business;
    public EventRequestPanel(JPanel workArea, HostOrganization organization, Business business) {
        initComponents();
        this.workArea = workArea;
        this.organization = organization;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eventnametxt = new javax.swing.JTextField();
        eventtypetxt = new javax.swing.JTextField();
        eventdatetxt = new javax.swing.JTextField();
        eventtimetxt = new javax.swing.JTextField();
        capacitytxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        budgettxt = new javax.swing.JTextField();
        createbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel2.setText("Type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel3.setText("Date :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel4.setText("Time : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel6.setText("Event Capacity : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
        add(eventnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 105, -1));
        add(eventtypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 105, -1));
        add(eventdatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 105, -1));
        add(eventtimetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 105, -1));

        capacitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacitytxtActionPerformed(evt);
            }
        });
        add(capacitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 105, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel9.setText("Create Event");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel10.setText("Budget :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));
        add(budgettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 105, -1));

        createbtn.setText("Create Event");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });
        add(createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 43, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void capacitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacitytxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_capacitytxtActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        Event newEvent = business.getEventDirectory().addEvent(eventnametxt.getText(), eventtypetxt.getText(), organization, eventdatetxt.getText(), eventtimetxt.getText(), Integer.parseInt(capacitytxt.getText()));
        organization.getHostedEvents().add(newEvent);
        JOptionPane.showMessageDialog(this, "Created Event..");
    }//GEN-LAST:event_createbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgettxt;
    private javax.swing.JTextField capacitytxt;
    private javax.swing.JButton createbtn;
    private javax.swing.JTextField eventdatetxt;
    private javax.swing.JTextField eventnametxt;
    private javax.swing.JTextField eventtimetxt;
    private javax.swing.JTextField eventtypetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
