/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.host;

import Business.Business;
import Business.Enterprise.Event;
import Business.Enterprise.EventStatusEnum;
import Business.Organization.EventManagementOrganization.EventManagementOrganization;
import Business.Organization.HostOrganization.HostOrganization;
import Business.Organization.Organization;
import Business.Roles.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.Admin.AdminJPanel;
import ui.eventManagement.ManageEventJPanel;
import ui.host.ManageEventPanel;

/**
 *
 * @author godalla
 */
public class HostJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HostJPanel
     */
    JPanel workArea;
    Business business;
    HostOrganization organization;
    UserAccount userAccount;
    
    public HostJPanel(JPanel userProcessContainer, UserAccount userAccount, HostOrganization organization, Business business) {
        initComponents();
        this.workArea = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organization = organization;
        txtName.setText(userAccount.getPerson().getName());
        txtOrganization.setText(organization.getOrganizationName());
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateEvent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHostedEvents = new javax.swing.JTable();
        btnManageEvent = new javax.swing.JButton();
        btnViewGuests = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Host ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 71, 39));

        btnCreateEvent.setText("Create Event Request");
        btnCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEventActionPerformed(evt);
            }
        });
        add(btnCreateEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        tblHostedEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Type", "Event Date", "Event Time", "Event Capacity"
            }
        ));
        jScrollPane1.setViewportView(tblHostedEvents);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 547, 110));

        btnManageEvent.setText("Delegate Event Management");
        btnManageEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEventActionPerformed(evt);
            }
        });
        add(btnManageEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 262, -1));

        btnViewGuests.setText("View Guests");
        btnViewGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGuestsActionPerformed(evt);
            }
        });
        add(btnViewGuests, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel4.setText("Organization:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        add(txtOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, -1));

        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEventActionPerformed
        // TODO add your handling code here:
        EventRequestPanel eventRequestPanel = new EventRequestPanel(workArea, organization, business);
        workArea.add("CreateEventJPanel", eventRequestPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCreateEventActionPerformed

    private void btnManageEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEventActionPerformed
        // TODO add your handling code here:
       //int tableSize = tblHostedEvents.getRowCount();
       int selectedRow = tblHostedEvents.getSelectionModel().getLeadSelectionIndex();
       if(selectedRow<0){
           JOptionPane.showMessageDialog(this, "Please Select a Row");
           return;
       }
       Event selectedEvent = (Event) tblHostedEvents.getValueAt(selectedRow, 0);
       
       if(selectedEvent == null)
           return;
       if(selectedEvent.getEventManagement()!=null){
           JOptionPane.showMessageDialog(this,"Event Management Organization has already been Set!!");
           return;
       }
       
       ManageEventPanel manageEventPanel = new ManageEventPanel(workArea, organization, business, selectedEvent);
   
        workArea.add("ManageEventJPanel", manageEventPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
       
       
    }//GEN-LAST:event_btnManageEventActionPerformed

    private void btnViewGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGuestsActionPerformed
        // TODO add your handling code here:
        
       int selectedRow = tblHostedEvents.getSelectionModel().getLeadSelectionIndex();
       if(selectedRow<0){
           JOptionPane.showMessageDialog(this, "Please Select a Row");
           return;
       }
       Event selectedEvent = (Event) tblHostedEvents.getValueAt(selectedRow, 0);
       
       if(selectedEvent == null)
           return;
       
       GuestListJPanel manageEventPanel = new GuestListJPanel(workArea,selectedEvent, business.getUserAccountDirectory());
   
        workArea.add("ManageEventJPanel", manageEventPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnViewGuestsActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblHostedEvents.getModel();
        model.setRowCount(0);
        
        for(Event event: organization.getHostedEvents()){
                Object[] row = new Object[5];
                row[0] = event;
                row[1] = event.getType();
                row[2] = event.getDate();
                row[3] = event.getTime();
                row[4] = event.getEventCapacity();
            
                model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEvent;
    private javax.swing.JButton btnManageEvent;
    private javax.swing.JButton btnViewGuests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHostedEvents;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    // End of variables declaration//GEN-END:variables

}
