/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.host;

import Business.Business;
import Business.Enterprise.Event;
import Business.Enterprise.EventStatusEnum;
import Business.Organization.EventManagementOrganization.EventManagementOrganization;
import Business.Organization.HostOrganization.HostOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitin
 */
public class ManageEventPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEventPanel
     */
    JPanel workArea;
    Business business;
    HostOrganization organization;
    Event event;
    public ManageEventPanel(JPanel workArea, HostOrganization organization, Business business, Event event) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.organization = organization;
        this.event = event;
        
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventOrganization = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelegate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEventOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Name", "Number of Events"
            }
        ));
        jScrollPane1.setViewportView(tblEventOrganization);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 140));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("List of Event Organizations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 30));

        btnDelegate.setText("Delegate");
        btnDelegate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelegateActionPerformed(evt);
            }
        });
        add(btnDelegate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, 30));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelegateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelegateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEventOrganization.getSelectionModel().getLeadSelectionIndex();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a Row");
            return;
        }
        EventManagementOrganization eventOrganization = (EventManagementOrganization) tblEventOrganization.getValueAt(selectedRow, 0);
        eventOrganization.getManagedEvents().add(event);
        event.setEventManagement(eventOrganization);
        event.setStatus(EventStatusEnum.Accepted);
        JOptionPane.showMessageDialog(this, "Assigned successfully");
        initTable();
    }//GEN-LAST:event_btnDelegateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblEventOrganization.getModel();
        
        model.setRowCount(0);
        EventManagementOrganization mOrganization = null;
        for(Organization organization: business.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof EventManagementOrganization){
                mOrganization = (EventManagementOrganization) organization;
                Object[] row = new Object[2];
                row[0] = mOrganization;
                row[1] = mOrganization.getManagedEvents().size();
                
                model.addRow(row);
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelegate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventOrganization;
    // End of variables declaration//GEN-END:variables
}
