/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTheBusiness;

import UserInterface.ProductManagement.*;
import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.ChannelCatalog;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.MarketCatalog;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageTheBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Market selectedMarket;
    MarketCatalog marketCatalog;
    ChannelCatalog channelCatalog;
    Channel selectedChannel;
    public ManageTheBusinessJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        this.marketCatalog = business.getMarketCatalog();
        this.channelCatalog = business.getChannelCatalog();
        refreshTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarketCatalog = new javax.swing.JTable();
        txtMarketName = new javax.swing.JTextField();
        btnAddMarket = new javax.swing.JButton();
        btnAddChannel = new javax.swing.JButton();
        txtChannelName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChannelCatalog = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setText("Xerox");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage The Business");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, -1));

        tblMarketCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Markets"
            }
        ));
        tblMarketCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMarketCatalogMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMarketCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 490, 140));

        txtMarketName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketNameActionPerformed(evt);
            }
        });
        add(txtMarketName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 170, -1));

        btnAddMarket.setText("Add New Market");
        btnAddMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarketActionPerformed(evt);
            }
        });
        add(btnAddMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        btnAddChannel.setText("Add New Channel");
        btnAddChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChannelActionPerformed(evt);
            }
        });
        add(btnAddChannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        txtChannelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChannelNameActionPerformed(evt);
            }
        });
        add(txtChannelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 170, -1));

        tblChannelCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Channel"
            }
        ));
        tblChannelCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblChannelCatalogMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblChannelCatalog);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 490, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void txtMarketNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMarketNameActionPerformed

    private void tblMarketCatalogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMarketCatalogMousePressed
        // TODO add your handling code here:
        int marketTableSize = tblMarketCatalog.getRowCount();
        int selectedrow = tblMarketCatalog.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > marketTableSize - 1) {
            return;
        }
        selectedMarket = (Market) tblMarketCatalog.getValueAt(selectedrow, 0);
        if (selectedMarket == null) {
            return;
        }

        
    }//GEN-LAST:event_tblMarketCatalogMousePressed

    private void btnAddMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarketActionPerformed
        // TODO add your handling code here:
        String marketName = txtMarketName.getText();
        marketCatalog.newMarket(marketName);
        JOptionPane.showMessageDialog(this,"Market Added");
        refreshTable();
    }//GEN-LAST:event_btnAddMarketActionPerformed

    private void btnAddChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChannelActionPerformed
        // TODO add your handling code here:
        String marketName = txtChannelName.getText();
        channelCatalog.newChannel(marketName);
        JOptionPane.showMessageDialog(this,"Market Added");
        refreshTable();
    }//GEN-LAST:event_btnAddChannelActionPerformed

    private void txtChannelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChannelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChannelNameActionPerformed

    private void tblChannelCatalogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChannelCatalogMousePressed
        // TODO add your handling code here:
        int channelTableSize = tblChannelCatalog.getRowCount();
        int selectedrow = tblChannelCatalog.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > channelTableSize - 1) {
            return;
        }
        selectedChannel = (Channel) tblChannelCatalog.getValueAt(selectedrow, 0);
        if (selectedChannel == null) {
            return;
        }

    }//GEN-LAST:event_tblChannelCatalogMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnAddChannel;
    private javax.swing.JButton btnAddMarket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblChannelCatalog;
    private javax.swing.JTable tblMarketCatalog;
    private javax.swing.JTextField txtChannelName;
    private javax.swing.JTextField txtMarketName;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
            ArrayList<Market> marketList = business.getMarketCatalog().getMarkets();

        if (marketList.isEmpty()) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tblMarketCatalog.getModel();
        model.setRowCount(0);
        for (Market market : marketList) {
                Object[] row = new Object[1];
                row[0] = market;
                model.addRow(row);
            }
        
        
        ArrayList<Channel> channelList = (ArrayList)business.getChannelCatalog().getChannelList();

        if (channelList.isEmpty()) {
            return;
        }
        DefaultTableModel model1 = (DefaultTableModel)tblChannelCatalog.getModel();
        model1.setRowCount(0);
        for (Channel channel : channelList) {
                Object[] row = new Object[1];
                row[0] = channel;
                model1.addRow(row);
            }
        }
    }
