/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.CourseCatalog.CourseCatalog;
import Model.CourseSchedule.SeatAssignment;
import Model.CourseSchedule.CourseLoad;
import Model.CourseSchedule.CourseOffer;
import Model.CourseSchedule.CourseSchedule;
import Model.CourseSchedule.Seat;
import Model.People.Student;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godalla
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    Student student;
    CourseLoad courseLoad;
    JPanel workArea;
    CourseSchedule courseSchedule;
    CourseCatalog courseCatalog;
    String semester;
    
    public CourseRegistrationJPanel(JPanel workArea, Student student, CourseLoad courseLoad, CourseCatalog courseCatalog, String semester) {
        initComponents();
        this.courseLoad = courseLoad;
        this.student = student;
        this.workArea = workArea;
//        this.courseSchedule = courseSchedule;
        this.courseSchedule = student.getCourseSchedule();
        this.courseCatalog =  courseCatalog;
        currentsemtxt.setText(semester);
        populateTable(courseLoad.getCourseOffers());
    }
     private void populateTable(List<CourseOffer> courseOffers) {
        DefaultTableModel acctTbl = (DefaultTableModel) tableCourseOffers.getModel();
        acctTbl.setRowCount(0);
        for(CourseOffer courseOffer : courseOffers){
            Object[] row = new Object[7];
            row[0] = courseOffer;
            row[1] = courseOffer.getCourse().getCourseID();
            row[2] = String.valueOf(courseOffer.getCourse().getCredits());
            row[3] = String.valueOf(courseOffer.getSeatList().size());
            row[4] = courseOffer.getProfessor();
            row[5] = String.valueOf(courseOffer.getProfessor().getRating());
            row[6] = courseOffer.getTiming();
            acctTbl.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentsemtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourseOffers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchcoursenumbertxt = new javax.swing.JTextField();
        searchprofessortxt = new javax.swing.JTextField();
        searchlanguagetxt = new javax.swing.JTextField();
        searchbyCNumberbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        searchbyProfessorbtn = new javax.swing.JButton();
        searchbyLanguagebtn = new javax.swing.JButton();
        btnListAllCourses = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Course Registeration ");

        jLabel2.setText("Registeration open for Semester :");

        tableCourseOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Course Number", "Credits", "Seats Left", "Professor", "Professor Rating", "Schedule"
            }
        ));
        jScrollPane1.setViewportView(tableCourseOffers);

        jLabel3.setText("Search By Course Number");

        jLabel5.setText("Search By Professor ");

        jLabel6.setText("Search By Language");

        searchbyCNumberbtn.setText("Search ");
        searchbyCNumberbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyCNumberbtnActionPerformed(evt);
            }
        });

        Registerbtn.setText("Register");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        searchbyProfessorbtn.setText("Search ");
        searchbyProfessorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyProfessorbtnActionPerformed(evt);
            }
        });

        searchbyLanguagebtn.setText("Search ");
        searchbyLanguagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyLanguagebtnActionPerformed(evt);
            }
        });

        btnListAllCourses.setText("List All Course");
        btnListAllCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllCoursesActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchlanguagetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(searchprofessortxt)
                                    .addComponent(searchcoursenumbertxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchbyCNumberbtn)
                                    .addComponent(searchbyProfessorbtn)
                                    .addComponent(searchbyLanguagebtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77)
                                .addComponent(currentsemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 207, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Registerbtn)
                        .addGap(34, 34, 34)
                        .addComponent(btnListAllCourses)
                        .addGap(21, 21, 21)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentsemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registerbtn)
                    .addComponent(btnListAllCourses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchcoursenumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbyCNumberbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(searchprofessortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbyProfessorbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(searchlanguagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbyLanguagebtn))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel acctTbl = (DefaultTableModel) tableCourseOffers.getModel();
        int selectedRow = tableCourseOffers.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a course");
            return;
        }
        CourseOffer registeringCourse = (CourseOffer) acctTbl.getValueAt(selectedRow,0);
        if(courseSchedule.getStudentCourses().contains(registeringCourse)){
            JOptionPane.showMessageDialog(this,"Already registered");
            return;
        }
        SeatAssignment newSeatAssignment = new SeatAssignment(registeringCourse, student);
        Seat newSeat = newSeatAssignment.assignSeat(registeringCourse, student);
        if(newSeat==null){
            JOptionPane.showMessageDialog(this, "The selected course is full!");
            return;
        }
        courseSchedule.getStudentCourses().add(registeringCourse);
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void searchbyCNumberbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyCNumberbtnActionPerformed
        // TODO add your handling code here:
        CourseOffer courseOffer = courseLoad.getCourseOffer(courseCatalog.getCourseByID(searchcoursenumbertxt.getText()));
        List<CourseOffer> courseOffers= new ArrayList<>();
        courseOffers.add(courseOffer);
        populateTable(courseOffers);
    }//GEN-LAST:event_searchbyCNumberbtnActionPerformed

    private void searchbyProfessorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyProfessorbtnActionPerformed
        // TODO add your handling code here:
        List<CourseOffer> courseOffers = courseLoad.getCourseOfferByProf(searchprofessortxt.getText());
        populateTable(courseOffers);
    }//GEN-LAST:event_searchbyProfessorbtnActionPerformed

    private void searchbyLanguagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyLanguagebtnActionPerformed
        // TODO add your handling code here:
        List<CourseOffer> courseOffers = courseLoad.getCourseOfferByLanguage(searchlanguagetxt.getText());
        populateTable(courseOffers);
    }//GEN-LAST:event_searchbyLanguagebtnActionPerformed

    private void btnListAllCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllCoursesActionPerformed
        // TODO add your handling code here:
         populateTable(courseLoad.getCourseOffers());
    }//GEN-LAST:event_btnListAllCoursesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registerbtn;
    private javax.swing.JButton btnListAllCourses;
    private javax.swing.JTextField currentsemtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbyCNumberbtn;
    private javax.swing.JButton searchbyLanguagebtn;
    private javax.swing.JButton searchbyProfessorbtn;
    private javax.swing.JTextField searchcoursenumbertxt;
    private javax.swing.JTextField searchlanguagetxt;
    private javax.swing.JTextField searchprofessortxt;
    private javax.swing.JTable tableCourseOffers;
    // End of variables declaration//GEN-END:variables
}
