/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import Model.CourseCatalog.CourseCatalog;
import Model.CourseSchedule.CourseLoad;
import Model.Faculty.ProfessorDirectory;
import Model.People.StudentDirectory;
import Model.Persona.User;
import Model.Persona.UserDirectory;
import Model.Persona.Validations;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author godalla
 */
public class LoginJPanel extends javax.swing.JPanel {

    private JPanel WorkArea;
    private StudentDirectory studentDirectory;
    private UserDirectory userDirectory;
    private ProfessorDirectory professorDirectory;
    private CourseLoad courseLoad;
    private CourseCatalog courseCatalog;
    private String semester;
    
    LoginJPanel(JPanel WorkArea, StudentDirectory studentDirectory, UserDirectory userDirectory, ProfessorDirectory professorDirectory, CourseLoad courseLoad, CourseCatalog courseCatalog, String semester) {
        initComponents();
        this.WorkArea = WorkArea;
        this.studentDirectory = studentDirectory;
        this.professorDirectory = professorDirectory;
        this.userDirectory =  userDirectory;
        this.courseLoad = courseLoad;
        this.courseCatalog = courseCatalog;
        this.semester = "Fall2023";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();
        passwordtxt = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN PAGE");

        lblUserName.setText("Username :");

        lblPwd.setText("Password :");

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("New user : ");

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerbtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginbtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblUserName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPwd)
                                            .addGap(1, 1, 1)))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(passwordtxt)))))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginbtn)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(registerbtn))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String username = usernametxt.getText();
        String password = passwordtxt.getText();
        boolean flag = false;
        if(username.equals("admin") && password.equals("password")){
            AdminJpanel adminPanel = new AdminJpanel(WorkArea, professorDirectory, studentDirectory, semester, courseCatalog);
            WorkArea.add("AdminPanel", adminPanel);
            CardLayout layout = (CardLayout) WorkArea.getLayout();
            layout.next(WorkArea);
            flag = true;
        }
        for(User u: userDirectory.getUserList()){
            if(u.getUserID().equals(username) && u.getPassword().equals(Validations.passwordHashing(password))){
       
                if(u.getRole().equals("Student")){
                    StudentDashboardJPanel studentDashboard = new StudentDashboardJPanel(WorkArea, studentDirectory.findStudent(u.getPlatformID()), u, courseLoad, courseCatalog, semester);
                    System.out.println(u.getPlatformID());
                    System.out.println(studentDirectory.findStudent(u.getPlatformID()));
                    WorkArea.add("StudentDashboard", studentDashboard);
                    CardLayout layout = (CardLayout) WorkArea.getLayout();
                    layout.next(WorkArea);
                    flag = true;
                }
                else{
                    ProfessorDashboardJPanel professorDashboard = new ProfessorDashboardJPanel(WorkArea, professorDirectory.findProfessor(u.getPlatformID()), u, courseLoad, studentDirectory,courseCatalog, semester);
                    WorkArea.add("ProfessorDashboard", professorDashboard);
                    CardLayout layout = (CardLayout) WorkArea.getLayout();
                    layout.next(WorkArea); 
                    flag = true;
                }
            }
            }
        if(!flag){
                JOptionPane.showMessageDialog(this,"Invalid Username or Password");
                return;
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
        RegisterJPanel registerJPanel = new RegisterJPanel(WorkArea, studentDirectory, userDirectory, professorDirectory);
        WorkArea.add("LoginJPanel", registerJPanel);
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.next(WorkArea);
    }//GEN-LAST:event_registerbtnActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
