/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.CourseSchedule.CourseLoad;
import Model.CourseSchedule.CourseOffer;
import Model.CourseSchedule.Seat;
import Model.People.Student;
import Model.People.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godalla
 */
public class ProfessorManageCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorManageCourseJPanel
     */
    JPanel workArea;
    CourseLoad courseLoad;
    CourseOffer courseOffer;
    StudentDirectory studentDirectory;
    public ProfessorManageCourseJPanel(JPanel workArea, CourseLoad courseLoad, CourseOffer courseOffer, StudentDirectory studentDirectory) {
        initComponents();
        this.courseLoad = courseLoad;
        this.workArea = workArea;
        this.courseOffer = courseOffer;
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        model.setRowCount(0);
        for(Seat seat: courseOffer.getSeatList()){
            if(seat!=null && seat.getStudent()!=null){
                Student student = seat.getStudent();
                Object[] row = new Object[4];
                row[0] = student;
                row[1] = student.getStudentID();
                row[2] = seat.getGrade();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gradetxt = new javax.swing.JTextField();
        gradebtn = new javax.swing.JButton();
        deletestudentbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Professor Manage Course ");

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "NUID", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblStudent);

        jLabel2.setText("List of Students");

        jLabel3.setText("Student Grade :");

        gradebtn.setText("Grade");
        gradebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradebtnActionPerformed(evt);
            }
        });

        deletestudentbtn.setText("Delete Student");
        deletestudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudentbtnActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gradebtn)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deletestudentbtn))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletestudentbtn))
                .addGap(18, 18, 18)
                .addComponent(gradebtn)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletestudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudentbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        int selectedRow = tblStudent.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a student");
            return;
        }
        Student student = (Student) model.getValueAt(selectedRow,0);
        student.getCourseSchedule().getStudentCourses().remove(courseOffer);
        for(Seat st: courseOffer.getSeatList()){
            if(st.getStudent()==student){
                st.setStudent(null);
                st.setIsOccupied(false);
                st.setGrade("");
                JOptionPane.showMessageDialog(this,"Student Deleted");
                return;
            }
        }
        
    }//GEN-LAST:event_deletestudentbtnActionPerformed

    private void gradebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradebtnActionPerformed
        // TODO add your handling code here:
        String grade = gradetxt.getText();
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        int selectedRow = tblStudent.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a student");
            return;
        }
        Student student = (Student) model.getValueAt(selectedRow,0);
        for(Seat st: courseOffer.getSeatList()){
            if(st.getStudent()==student){
                st.setGrade(grade);
                return;
            }
        }
        for(Seat seat: courseOffer.getSeatList()){
            if(seat!=null && seat.getStudent()!=null){
                Student student1 = seat.getStudent();
                Object[] row = new Object[4];
                row[0] = student1;
                row[1] = student1.getStudentID();
                row[2] = seat.getGrade();
                model.addRow(row);
            }
        }
        JOptionPane.showMessageDialog(this,"Graded Succesffuly");
    }//GEN-LAST:event_gradebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletestudentbtn;
    private javax.swing.JButton gradebtn;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    // End of variables declaration//GEN-END:variables
}
