/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Faculty.Professor;
import Model.Faculty.ProfessorDirectory;
import Model.People.Person;
import Model.People.Student;
import Model.People.StudentDirectory;
import Model.Persona.User;
import Model.Persona.UserDirectory;
import Model.Persona.Validations;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author godalla
 */
public class RegisterJPanel extends javax.swing.JPanel {

    private JPanel WorkArea;
    private StudentDirectory studentDirectory;
    private UserDirectory userDirectory;
    private ProfessorDirectory professorDirectory;
   
    RegisterJPanel(JPanel WorkArea, StudentDirectory studentDirectory, UserDirectory userDirectory, ProfessorDirectory professorDirectory) {
        this.WorkArea =  WorkArea;
        this.studentDirectory = studentDirectory;
        this.professorDirectory = professorDirectory;
        this.userDirectory =  userDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleRegistration = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        lblUserId = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtGovtId = new javax.swing.JTextField();
        lblGovtId = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        dropDownRole = new javax.swing.JComboBox<>();
        registerbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblPlatformId = new javax.swing.JLabel();
        txtPlatformId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passwordtxt = new javax.swing.JPasswordField();

        titleRegistration.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleRegistration.setText("Registration Panel");

        lblUserId.setText("User ID :");

        lblPwd.setText("Password :");

        txtGovtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGovtIdActionPerformed(evt);
            }
        });

        lblGovtId.setText("Government ID :");

        lblRole.setText("Role :");

        dropDownRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Student", "Professor", "" }));
        dropDownRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownRoleActionPerformed(evt);
            }
        });

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Person ID:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Email:");

        jLabel5.setText("Phone Number:");

        jLabel6.setText("Address:");

        lblPlatformId.setText("Platform Id:");

        txtPlatformId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatformIdActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(titleRegistration))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(registerbtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGovtId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownRole, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlatformId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGovtId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRole, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPersonId)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtEmail)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtPlatformId, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(titleRegistration)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatformId)
                    .addComponent(txtPlatformId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserId)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGovtId)
                    .addComponent(txtGovtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropDownRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addComponent(registerbtn)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
        if(!Validations.isNumber(txtPersonId.getText())||!Validations.isNumber(txtPhoneNumber.getText()) || !Validations.isNumber(txtPlatformId.getText())){
            JOptionPane.showMessageDialog(this,"Incorrect Input Format");
            return;
        }
        for(User user: userDirectory.getUserList()){
            if(user.getUserID().equals(usernametxt.getText())){
                JOptionPane.showMessageDialog(this,"USER ID already exists.");
                return;
            }
        }
        for(Student student: studentDirectory.getStudentlist()){
            if(student.getStudentID()==Integer.parseInt(txtPlatformId.getText())){
                JOptionPane.showMessageDialog(this,"Student ID already exists.");
                return;
            }
        }
        for(Professor professor: professorDirectory.getTeacherlist()){
            if(professor.getProfessorID()==Integer.parseInt(txtPlatformId.getText())){
                JOptionPane.showMessageDialog(this,"Professor ID already exists.");
                return;
            }
        }
        String role = dropDownRole.getSelectedItem().toString();
        
        Person person = new Person(Integer.parseInt(txtPersonId.getText()), txtFirstName.getText(), txtLastName.getText(), txtAddress.getText(), txtEmail.getText(), Integer.parseInt(txtPhoneNumber.getText()));
        User user = userDirectory.newUserAccount(person);
        user.setUserID(usernametxt.getText());
        user.setPassword(Validations.passwordHashing(passwordtxt.getText()));
        user.setPlatformID(Integer.parseInt(txtPlatformId.getText()));
        user.setRole(role);
        if(role.equals("Student")){
            Student student = studentDirectory.newStudentProfile(person);
            student.setStudentID(Integer.parseInt(txtPlatformId.getText()));
            
        }else if(role.equals("Professor")){
            Professor professor = professorDirectory.newFacultyProfile(person,Integer.parseInt(txtPlatformId.getText()));
        }
        
        
         JOptionPane.showMessageDialog(this, "Added account successfully");
        
        WorkArea.remove(this);
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
        
    }//GEN-LAST:event_registerbtnActionPerformed

    private void dropDownRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownRoleActionPerformed

    private void txtGovtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGovtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGovtIdActionPerformed

    private void txtPlatformIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatformIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatformIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropDownRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblGovtId;
    private javax.swing.JLabel lblPlatformId;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton registerbtn;
    private javax.swing.JLabel titleRegistration;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGovtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPersonId;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPlatformId;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
