/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Business.Business;
import Business.Data.DataStore;
import Business.Organization.EventManagementOrganization.EventManagementOrganization;
import Business.Organization.HostOrganization.HostOrganization;
import static Business.Organization.Organization.OrganizationType.ServiceOrganization;
import Business.Organization.ServiceOrganization.ServiceOrganization;
import Business.Organization.VendorOrganization.VendorOrganization;
import Business.Organization.VenueOrganization.VenueOrganization;
import Business.Roles.UserAccount;
import Business.Roles.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.Admin.AdminJPanel;
import ui.eventManagement.EventManagementJPanel;
import ui.guest.GuestJPanel;
import ui.host.HostJPanel;
import ui.service.ServiceJPanel;
import ui.vendor.VendorJPanel;
import ui.venue.VenueJPanel;

/**
 *
 * @author godalla
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Business business;
    
    public MainJFrame() {
        initComponents();
        DataStore ds = new DataStore();
        business = ds.initializeBusiness();
//        business = Business.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JPasswordField();
        workArea = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Event Management");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 36));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 84, -1));

        jLabel1.setText("Username :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel3.setText("Password :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
        jPanel3.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 84, -1));
        jPanel3.add(pwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 85, -1));

        jSplitPane1.setTopComponent(jPanel3);

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username  = usernametxt.getText();
        String password = pwdtxt.getText();

        //call dashboard
        UserAccountDirectory userAccountDirectory = business.getUserAccountDirectory();
        UserAccount user = userAccountDirectory.authenticateUser(username, password);

        if(user==null){
            JOptionPane.showMessageDialog(this, "Invalid Credentials");
            return;
        }

        String role = user.getRole().getType().getValue();

        if(role==null){
            JOptionPane.showMessageDialog(this, "Invalid Credentials");
            return;
        }

        if(role.equals("Admin")){
            JPanel AdminJPanel = new AdminJPanel(workArea, business);
            workArea.removeAll();
            workArea.add("AdminJPanel", AdminJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("VendorManager")){
            VendorJPanel vendorJPanel = new VendorJPanel(workArea,user,(VendorOrganization)user.getOrganization(), business);
            workArea.removeAll();
            workArea.add("VendorJPanel", vendorJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("VenueManager")){
            VenueJPanel venueJPanel = new VenueJPanel(workArea, user,(VenueOrganization)user.getOrganization(),business);
            workArea.removeAll();
            workArea.add("VenueJPanel", venueJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("EventManager")){
            EventManagementJPanel eventOrganizerJPanel = new EventManagementJPanel(workArea,user,(EventManagementOrganization)user.getOrganization(), business);
            workArea.removeAll();
            workArea.add("EventOrganizerJPanel", eventOrganizerJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("ServiceManager")){
            ServiceJPanel serviceJPanel = new ServiceJPanel(workArea,user,(ServiceOrganization)user.getOrganization(), business);
            workArea.removeAll();
            workArea.add("EventOrganizerJPanel", serviceJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("HostManager")){
            HostJPanel hostJPanel = new HostJPanel(workArea, user,(HostOrganization)user.getOrganization(),business);
            workArea.removeAll();
            workArea.add("HostJPanel", hostJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }else if(role.equals("Employee")){

        }else if(role.equals("Guest")){
            GuestJPanel guestJPanel = new GuestJPanel(workArea, user,business);
            workArea.removeAll();
            workArea.add("GuestJPanel", guestJPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);

        }
        //       System.out.println("ui.MainJFrame.btnLoginActionPerformed()-"+"role - "+user.getRole().getType().getValue());
        //       System.out.println("ui.MainJFrame.btnLoginActionPerformed()-"+"org - "+user.getOrganization().getType());
        //       workArea.removeAll();
        //
        //       workArea.add("workArea", user.getRole().createWorkArea(workArea, user, user.getOrganization(), business));
        //       CardLayout layout = (CardLayout) workArea.getLayout();
        //      layout.next(workArea);

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPasswordField pwdtxt;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
