/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.venue;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.VenueOrganization.VenueOrganization;
import Business.Organization.VenueOrganization.VenueOrganization.VenueAvailability;
import Business.Roles.UserAccount;
import java.util.HashSet;
import javax.swing.JPanel;

/**
 *
 * @author snehayenduri
 */
public class VenueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VenueJPanel
     */
    JPanel workArea;
    Business business;
    VenueOrganization organization;
    UserAccount userAccount;
    public VenueJPanel(JPanel userProcessContainer, UserAccount userAccount, VenueOrganization organization, Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.organization = organization;
        this.userAccount = userAccount;
        txtName.setText(userAccount.getPerson().getName());
        txtOrganization.setText(organization.getOrganizationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbAvailability = new javax.swing.JComboBox<>();
        btnAvailability = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Venue Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        cmbAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        add(cmbAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 165, -1));

        btnAvailability.setText("Set Availability");
        btnAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilityActionPerformed(evt);
            }
        });
        add(btnAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 120, -1));

        jLabel4.setText("Organization:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        add(txtOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, -1));

        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilityActionPerformed
        // TODO add your handling code here:
        String availability = (String) cmbAvailability.getSelectedItem();
        if(availability.equals("Available")){
            organization.setAvailability(VenueAvailability.Available);
        }
        else{
            organization.setAvailability(VenueAvailability.Unavailable);
        }
    }//GEN-LAST:event_btnAvailabilityActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailability;
    private javax.swing.JComboBox<String> cmbAvailability;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    // End of variables declaration//GEN-END:variables
}
