/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.service;

import Business.Business;
import Business.Enterprise.Event;
import Business.Organization.Organization;
import Business.Organization.ServiceOrganization.ProductManagement.Product;
import Business.Organization.ServiceOrganization.ServiceOrganization;
import Business.Roles.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehayenduri
 */
public class ServiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceJPanel
     */
    JPanel workArea;
    Business business;
    ServiceOrganization organization;
    UserAccount userAccount;
    public ServiceJPanel(JPanel userProcessContainer, UserAccount userAccount, ServiceOrganization organization, Business business) {
        initComponents();
        this.workArea = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organization = organization;
        txtName.setText(userAccount.getPerson().getName());
        txtOrganization.setText(organization.getOrganizationName());
        initTable();
        initEventTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblServiceMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServiceMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblService);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 602, 105));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Service Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 120, -1));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 120, -1));

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event Name", "Host", "Event Type"
            }
        ));
        jScrollPane2.setViewportView(tblEvents);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 602, 116));

        jLabel2.setText("Product Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel3.setText("Product Cost");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jLabel4.setText("All Products");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel5.setText("Organization:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        add(txtOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, -1));

        jLabel6.setText("Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblServiceMouseEntered

    private void tblServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblServiceMousePressed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        organization.getProductCatalog().addNewProduct(txtProductName.getText(), Float.parseFloat(txtPrice.getText()));
        JOptionPane.showMessageDialog(this, "Added Product");
        txtPrice.setText("");
        txtProductName.setText("");
        initTable();
        
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblService.getModel();
        model.setRowCount(0);
        for(Product product: organization.getProductCatalog().getProductList()){
            Object[] row = new Object[2];
            row[0] = product;
            row[1] = product.getPrice();
            model.addRow(row);
        }
    }
    public void initEventTable(){
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        model.setRowCount(0);
        for(Event event: organization.getServicedEvents()){
            Object[] row = new Object[3];
            row[0] = event.getName();
            row[1] = event.getHost();
            row[2] = event.getType();
            
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEvents;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
