/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.ChannelCatalog;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.MarketCatalog;
import TheBusiness.MarketModel.MarketChannelAssignment;
import TheBusiness.MarketModel.MarketChannelComboCatalog;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductCatalog;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageSuppliersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;
    Channel selectedChannel;
    ChannelCatalog channelCatalog;
    MarketCatalog marketCatalog;
    Market selectedMarket;
    MarketChannelAssignment mc;
    MarketChannelComboCatalog marketChannelComboCatalog;
    MarketChannelAssignment selectedMarketChannel;

    public ManageSuppliersJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
        channelCatalog = business.getChannelCatalog();
        marketCatalog = business.getMarketCatalog();
        marketChannelComboCatalog = business.getMarketChannelComboCatalog();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChannelCatalog = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMarketCatalog = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMarketChannel = new javax.swing.JTable();
        btnCreateSolutionOffer = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tblChannelCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Channel"
            }
        ));
        tblChannelCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblChannelCatalogMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblChannelCatalog);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 270, 90));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Channel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 550, -1));

        tblMarketCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Markets"
            }
        ));
        tblMarketCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMarketCatalogMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblMarketCatalog);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 90));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("Create Market Channel Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 220, -1));

        tblMarketChannel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Market", "Channel"
            }
        ));
        jScrollPane3.setViewportView(tblMarketChannel);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 160));

        btnCreateSolutionOffer.setText("Create Solution Offer");
        btnCreateSolutionOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSolutionOfferActionPerformed(evt);
            }
        });
        add(btnCreateSolutionOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void tblChannelCatalogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChannelCatalogMousePressed
        // TODO add your handling code here:
        int channelTableSize = tblChannelCatalog.getRowCount();
        int selectedrow = tblChannelCatalog.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > channelTableSize - 1) {
            return;
        }
        selectedChannel = (Channel) tblChannelCatalog.getValueAt(selectedrow, 0);
        if (selectedChannel == null) {
            return;
        }


    }//GEN-LAST:event_tblChannelCatalogMousePressed

    private void tblMarketCatalogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMarketCatalogMousePressed
        // TODO add your handling code here:
        int marketTableSize = tblMarketCatalog.getRowCount();
        int selectedrow = tblMarketCatalog.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > marketTableSize - 1) {
            return;
        }
        selectedMarket = (Market) tblMarketCatalog.getValueAt(selectedrow, 0);
        if (selectedMarket == null) {
            return;
        }

    }//GEN-LAST:event_tblMarketCatalogMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedMarketRow = tblMarketCatalog.getSelectedRow();
        if(selectedMarketRow< 0){
            JOptionPane.showMessageDialog(this,"Select a Market");
            return;
        }
        selectedMarket = (Market) tblMarketCatalog.getValueAt(selectedMarketRow, 0);
        
        int selectedChannelRow = tblChannelCatalog.getSelectedRow();
        if(selectedChannelRow<0){
            JOptionPane.showMessageDialog(this,"Select a channel");
            return;
        }
        selectedChannel = (Channel) tblChannelCatalog.getValueAt(selectedChannelRow, 0);
        marketChannelComboCatalog.newMarketChannelCombo(selectedMarket, selectedChannel);
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCreateSolutionOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSolutionOfferActionPerformed
        // TODO add your handling code here:
        int selectedMarketChannelRow = tblMarketChannel.getSelectedRow();
        if(selectedMarketChannelRow<0){
            JOptionPane.showMessageDialog(this,"Select a MarketChannel Assignment");
            return;
        }
        selectedMarketChannel = (MarketChannelAssignment) tblMarketChannel.getValueAt(selectedMarketChannelRow, 0);
        
        SolutionOfferPanel iet = new SolutionOfferPanel(business, selectedMarketChannel, CardSequencePanel);
        CardSequencePanel.add("Create Solution Offer", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCreateSolutionOfferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnCreateSolutionOffer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblChannelCatalog;
    private javax.swing.JTable tblMarketCatalog;
    private javax.swing.JTable tblMarketChannel;
    // End of variables declaration//GEN-END:variables
    private void refreshTable() {
        ArrayList<Channel> channelList = (ArrayList)business.getChannelCatalog().getChannelList();

        if (channelList.isEmpty()) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tblChannelCatalog.getModel();
        model.setRowCount(0);
        for (Channel channel : channelList) {
                Object[] row = new Object[1];
                row[0] = channel;
                model.addRow(row);
            }
        ArrayList<Market> marketList = business.getMarketCatalog().getMarkets();

        if (marketList.isEmpty()) {
            return;
        }
        DefaultTableModel model1 = (DefaultTableModel)tblMarketCatalog.getModel();
        model1.setRowCount(0);
        for (Market market : marketList) {
                Object[] row = new Object[1];
                row[0] = market;
                model1.addRow(row);
            }
        
        ArrayList<MarketChannelAssignment> mcaList = business.getMarketChannelComboCatalog().getMcalist();
        if (mcaList.isEmpty()) {
            return;
        }
        DefaultTableModel model2 = (DefaultTableModel)tblMarketChannel.getModel();
        model2.setRowCount(0);
        for (MarketChannelAssignment mca : mcaList) {
                Object[] row = new Object[2];
                row[0] = mca;
                row[1] = mca.getChannel();
                model2.addRow(row);
            }
        }
  
        
}
