/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.eventManagement;

import Business.Business;
import Business.Enterprise.Event;
import Business.Organization.Organization;
import Business.Organization.ServiceOrganization.ProductManagement.Product;
import Business.Organization.ServiceOrganization.ServiceOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehayenduri
 */
public class AddServicesJPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form AddServicesJPanel2
     */
    JPanel workArea;
    Business business;
    Event event;
    
    public AddServicesJPanel2(JPanel workArea, Business business, Event event) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.event = event;
        populateComboBox();
    }
    
     public void populateComboBox(){
        ServiceComboBox.removeAllItems();
        for(Organization organization: business.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof ServiceOrganization)
             ServiceComboBox.addItem((ServiceOrganization) organization);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        ServiceComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblServiceMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServiceMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblService);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 602, 105));

        ServiceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceComboBoxActionPerformed(evt);
            }
        });
        add(ServiceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, -1));

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddProductItemActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 90, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Add Services");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblServiceMouseEntered

    private void tblServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblServiceMousePressed

    private void ServiceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceComboBoxActionPerformed
        // TODO add your handling code here:
        ServiceOrganization organization = (ServiceOrganization) ServiceComboBox.getSelectedItem();
        initTable(organization);

    }//GEN-LAST:event_ServiceComboBoxActionPerformed

    private void jButton1AddProductItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddProductItemActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblService.getSelectionModel().getLeadSelectionIndex();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please Select a Product");
            return;
        }

        Product product = (Product) tblService.getValueAt(selectedRow, 0);
        event.getProductList().add(product);
        ServiceOrganization organization = (ServiceOrganization) ServiceComboBox.getSelectedItem();
        organization.getServicedEvents().add(event);
        
        JOptionPane.showMessageDialog(this, "Order Placed..");
    }//GEN-LAST:event_jButton1AddProductItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void initTable(ServiceOrganization organization){
        DefaultTableModel model = (DefaultTableModel) tblService.getModel();
        model.setRowCount(0);
        for(Product product: organization.getProductCatalog().getProductList()){
            Object[] row = new Object[2];
            row[0] = product;
            row[1] = product.getPrice();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ServiceOrganization> ServiceComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblService;
    // End of variables declaration//GEN-END:variables
}
