/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.eventManagement;

import Business.Business;
import Business.Enterprise.Event;
import Business.Organization.Organization;
import Business.Organization.VenueOrganization.VenueOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitin
 */
public class AddVenueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVenueJPanel
     */
    Business business;
    JPanel workArea;
    Event event;
    public AddVenueJPanel(JPanel workArea, Business business, Event event) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.event = event;
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenue = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVenue = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Venue Name", "Availability"
            }
        ));
        jScrollPane1.setViewportView(tblVenue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 511, 184));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Add Venue");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        btnVenue.setText("Select Venue");
        btnVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenueActionPerformed(evt);
            }
        });
        add(btnVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 18, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenueActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVenue.getSelectionModel().getLeadSelectionIndex();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"Please select a venue");
            return;
        }
        VenueOrganization venue = (VenueOrganization) tblVenue.getValueAt(selectedRow,0);
        if(venue.getAvailability()==VenueOrganization.VenueAvailability.Unavailable){
            JOptionPane.showMessageDialog(this,"Please select an Available Venue!");
            return;
        }
        venue.getHostedEvents().add(event);
        event.setVenue(venue);
        JOptionPane.showMessageDialog(this, "Venue Added");
    }//GEN-LAST:event_btnVenueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblVenue.getModel();
        model.setRowCount(0);
        
        for(Organization organization: business.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof VenueOrganization){
                VenueOrganization vOrganization = (VenueOrganization)organization;
                Object[] row = new Object[2];
                row[0] = vOrganization;
                row[1] = vOrganization.getAvailability();
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVenue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenue;
    // End of variables declaration//GEN-END:variables
}
