/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import Business.AnalyticsReport;
import Business.Business;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Roles.Role;
import Business.Roles.UserAccount;
import Business.Roles.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author godalla
 */
public class AdminJPanel extends JPanel {

    /**
     * Creates new form AdminJPanel
     */
    JPanel workArea; 
    Business business;
    PersonDirectory pd;
    UserAccountDirectory ud;
    OrganizationDirectory od;
    
    public AdminJPanel(JPanel workArea, Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.pd = business.getPersonDirectory();
        this.ud = business.getUserAccountDirectory();
        this.od = business.getOrganizationDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnAddPerson = new javax.swing.JButton();
        btnOrg = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPersonName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        txtUserName = new javax.swing.JTextField();
        txtPwd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOrgId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxOrg = new javax.swing.JComboBox<>();
        txtAddress = new javax.swing.JTextField();
        txtOrgName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 34));

        btnAddPerson.setText("Add Person");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });
        add(btnAddPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        btnOrg.setText("Add Organization");
        btnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgActionPerformed(evt);
            }
        });
        add(btnOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 141, -1));

        btnAnalytics.setText("View Analytics Report");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });
        add(btnAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 176, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));
        add(txtPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 117, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 124, -1));

        jLabel3.setText("Email:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel4.setText("Role:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VendorManager", "VenueManager", "EventManager", "ServiceManager", "HostManager", "Guest" }));
        RoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleComboBoxActionPerformed(evt);
            }
        });
        add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 90, -1));
        add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 124, -1));

        jLabel5.setText("UserName:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel7.setText("Organization ID:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));
        add(txtOrgId, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 80, -1));

        jLabel8.setText("Organization Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel9.setText("Organization Address:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel10.setText("Organization Type:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        ComboBoxOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HostOrganization", "EventManagementOrganization", "ServiceOrganization", "VenueOrganization", "VendorOrganization" }));
        add(ComboBoxOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 140, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 95, -1));
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 98, -1));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void RoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleComboBoxActionPerformed
        // TODO add your handling code here:
        String role =(String)RoleComboBox.getSelectedItem();
        if(role.equals("Guest")){
            txtOrgId.enable(false);
        }else{
            txtOrgId.enable(true);
        }
    }//GEN-LAST:event_RoleComboBoxActionPerformed

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
         Person p =pd.createPerson(txtPersonName.getText());
         Role role = new Role() {
            @Override
            public JPanel createWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
                return null;
            }
        };
        String roleS= RoleComboBox.getSelectedItem().toString();
        role.setType(Role.RoleType.valueOf(roleS));
        UserAccount userAccount = ud.createUserAccount(txtUserName.getText(), txtPwd.getText(), p, role);
        userAccount.setRole(role);
        int orgId = Integer.parseInt(txtOrgId.getText());
        if(!roleS.equals("Guest")){
            userAccount.setOrganization(od.getOrganizationById(orgId));
        }
        JOptionPane.showMessageDialog(this, "Person Added");
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgActionPerformed
        // TODO add your handling code here:
        od.addOrganization(Organization.OrganizationType.valueOf((String)ComboBoxOrg.getSelectedItem()), txtOrgName.getText(), txtAddress.getText());
        JOptionPane.showMessageDialog(this, "Organization Added");
    }//GEN-LAST:event_btnOrgActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        // TODO add your handling code here:
        AnalyticsReport.findBestEventOrganization(od);
        AnalyticsReport.findHostOrganizationWithMostEvents(od);
        AnalyticsReport.findVenueWithMostEvents(od);
        AnalyticsReport.findTop3Events(business.getEventDirectory());
        AnalyticsReport.getTop3ExpensiveEvents(business.getEventDirectory());
    }//GEN-LAST:event_btnAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxOrg;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOrgId;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
