/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import Business.Business;
import Business.Person.Person;
import Business.Roles.Role;
import Business.Roles.UserAccount;
import Business.Roles.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehayenduri
 */
public class ManageUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserJPanel
     */
    JPanel workArea;
    Business business;
    UserAccountDirectory userAccountDirectory;
    public ManageUserJPanel(JPanel workArea, Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.userAccountDirectory = business.getUserAccountDirectory();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        Role = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        txtPwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 415));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manager User");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 510, -1));

        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel4.setText("Person Id:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));
        add(txtPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 174, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 174, -1));

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PersonId", "Username", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 341, 152));

        btnDelete.setText("Delete User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        Role.setText("Role:");
        add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "EventEmployee", "EventManager", "Guest", "HostManager", "ServiceEmployee", "ServiceManager", "VendorManager", "VenueManager" }));
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });
        add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 174, -1));
        add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 174, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUsers.getSelectedRow();
        if(selectedRow>=0){
            UserAccount userAccount = (UserAccount) tblUsers.getValueAt(selectedRow, 1);
            userAccountDirectory.deleteUser(userAccount);
            JOptionPane.showMessageDialog(this, "Deleted user succesfully!");
        }else{
            JOptionPane.showMessageDialog(this, "Please select a row",  "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        int personId = Integer.parseInt(txtPersonId.getText());
        Person p = business.getPersonDirectory().getPersonById(personId);
        String username = txtUsername.getText();
        String pwd = txtPwd.getText();
        Role role = (Role)roleComboBox.getSelectedItem();
        UserAccount userAccount = userAccountDirectory.createUserAccount(username, pwd, p, role);
        JOptionPane.showMessageDialog(this, "Added user "+userAccount.getPerson().getName()+ " succesfully!");
        
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtPersonId;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        List<UserAccount> users= userAccountDirectory.getUserAccountList();
        DefaultTableModel acctTbl = (DefaultTableModel) tblUsers.getModel();
        acctTbl.setRowCount(0);
        for(UserAccount ua : users){
            Object[] row = new Object[3];
            row[0] = ua.getPerson().getId();
            row[1] = ua;
            row[2] = ua.getRole().getType().getValue();
           
            acctTbl.addRow(row);
        }
    }
}
