/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.guest;

import Business.Business;
import Business.Enterprise.GuestEventRequest;
import Business.Organization.Organization;
import Business.Roles.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehayenduri
 */
public class GuestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestJPanel
     */
    JPanel workArea;
    Business business;
    UserAccount user;
    public GuestJPanel(JPanel workArea, UserAccount user, Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.user = user;
        initTable();
        for(GuestEventRequest eventRequest: user.getEventRequestList()){
            System.out.println(eventRequest.getEvent().getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Guest Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event Name", "Invitation Message", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(tblEvents);
        if (tblEvents.getColumnModel().getColumnCount() > 0) {
            tblEvents.getColumnModel().getColumn(0).setResizable(false);
            tblEvents.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, 145));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 127, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        model.setRowCount(0);
         System.out.println("ui.guest.GuestJPanel.initTable()"+user.getEventRequestList().size());
        for(GuestEventRequest eventRequest: user.getEventRequestList()){
            Object[] row = new Object[3];
            row[0] = eventRequest;
            row[1] = eventRequest.getMessage();
            row[2] = eventRequest.getStatus();
            model.addRow(row);
        }
    }
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEvents.getSelectionModel().getLeadSelectionIndex();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select an event");
            return;
        }
        GuestEventRequest eventRequest = (GuestEventRequest) tblEvents.getValueAt(selectedRow,0);
        if(eventRequest.getStatus()==GuestEventRequest.EventRequestStatus.Recieved){
            eventRequest.setStatus(GuestEventRequest.EventRequestStatus.Accepted);
            eventRequest.getEvent().getAcceptedGuestList().add(user);
            
        }
        else{
            JOptionPane.showMessageDialog(this,"This invitation has alreay been responded to!");
            return;
        }
        initTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEvents.getSelectionModel().getLeadSelectionIndex();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select an event");
            return;
        }
        GuestEventRequest eventRequest = (GuestEventRequest) tblEvents.getValueAt(selectedRow,0);
        if(eventRequest.getStatus()==GuestEventRequest.EventRequestStatus.Recieved){
            eventRequest.setStatus(GuestEventRequest.EventRequestStatus.Rejected);
        }
        else{
            JOptionPane.showMessageDialog(this,"This invitation has already been responded to!");
            return;
        }
        initTable();
        
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvents;
    // End of variables declaration//GEN-END:variables
}
